import HomeCourse1 from "../src/assets/images/home-course1.png";
import HomeCourse2 from "../src/assets/images/home-course2.png";
import HomeCourse3 from "../src/assets/images/home-course3.png";
import HomeCourse4 from "../src/assets/images/home-course4.png";
import HomeCourse5 from "../src/assets/images/home-course5.png";
import HomeCourse6 from "../src/assets/images/home-course6.png";
import sarah from "../src/assets/images/sarah.png";
import jason from "../src/assets/images/jason.png";
import emily from "../src/assets/images/emily.png";
import micheal from "../src/assets/images/micheal.png";
import webPic1 from "../src/assets/images/webpic1.png";
import webPic2 from "../src/assets/images/webpic2.png";
import webPic3 from "../src/assets/images/webpic3.png";
import uiPic1 from "../src/assets/images/uipic1.png";
import uiPic2 from "../src/assets/images/uipic2.png";
import uiPic3 from "../src/assets/images/uipic3.png";
import mobilePic1 from "../src/assets/images/mobilepic1.png";
import mobilePic2 from "../src/assets/images/mobilepic2.png";
import mobilePic3 from "../src/assets/images/mobilepic3.png";
import graphicPic1 from "../src/assets/images/graphicpic1.png";
import graphicPic2 from "../src/assets/images/graphicpic2.png";
import graphicPic3 from "../src/assets/images/graphicpic3.png";
import frontPic1 from "../src/assets/images/frontpic1.png";
import frontPic2 from "../src/assets/images/frontpic2.png";
import frontPic3 from "../src/assets/images/frontpic3.png";
import Aone from "../src/assets/images/Aone.png";
import Atwo from "../src/assets/images/Atwo.png";
import Athree from "../src/assets/images/Athree.png";
import Afour from "../src/assets/images/Afour.png";
import Bone from "../src/assets/images/Bone.png";
import Btwo from "../src/assets/images/Btwo.png";
import Bthree from "../src/assets/images/Bthree.png";
import Bfour from "../src/assets/images/Bfour.png";
import CourseDeatails from "../src/assets/images/coursedetails.png";
import furry1 from "./assets/images/furry-1.jpg";
import furry2 from "./assets/images/furry-2.jpg";
import furry3 from "./assets/images/furry-3.jpg";
import furry4 from "./assets/images/furry-4.jpg";
import furry5 from "./assets/images/furry5.jpg";
import furry6 from "./assets/images/furry6.jpg";
import furry7 from "./assets/images/furry7.jpg";
import furry8 from "./assets/images/furry8.jpg";

export const bestsellerz = [
  {
    id: 1,
    name: "Gevril Men's Watch",
    price: "$620.00",
  },
  {
    id: 2,
    name: "Favre-Leube Men's Watch",
    price: "$589.00",
  },
  {
    id: 3,
    name: "Fendi Women's Watch",
    price: "$1699.00",
  },
  {
    id: 4,
    name: "Hamilton Men's Watch",
    price: "$579.00",
  },
  {
    id: 5,
    name: "Raymond Weil Unisex Watch",
    price: "$579.00",
  },
  {
    id: 6,
    name: "Raymond Weil Unisex Watch",
    price: "$579.00",
  },
];

export const benefits = [
  {
    id: 1,
    title: "01",
    name: "Flexible Learning Schedule ",
    description:
      "Fit your coursework around your existing commitments and obligations.",
  },
  {
    id: 2,
    title: "02",
    name: "Expert Instruction",
    description:
      "Learn from industry experts who have hands-on experience in design and development.",
  },
  {
    id: 3,
    title: "03",
    name: "Diverse Course Offerings",
    description:
      "Explore a wide range of design and development courses covering various topics.",
  },
  {
    id: 4,
    title: "04",
    name: "Update Curriculum",
    description:
      "Access courses with up-to date content reflecting the latest trends and industry practices.",
  },
  {
    id: 5,
    title: "05",
    name: "Practical Projects and Assignments",
    description:
      "Fit your coursework around your existing commitments and obligations.",
  },
  {
    id: 6,
    title: "06",
    name: "Interactive Learning Environment",
    description:
      "Collaborate with fellow learners, exchanging ideas and feedback to enhance your understanding.",
  },
];

export const courseCards = [
  {
    id: "1",
    image: HomeCourse1,
    date: "4 Weeks",
    level: " Beginner",
    author: "By John Smith",
    title: "Web Design Fundamentals",
    description:
      "Learn the fundamentals of web design, including HTML, CSS, and responsive design principles. Develop the skills to create visually appealing and user-friendly websites.",
    btn: "Get Now ",
  },
  {
    id: "2",
    image: HomeCourse2,
    date: "6 Weeks",
    level: "Intermediate",
    author: "By Emily Johnson",
    title: "UI/UX Design",
    description:
      "Master the art of creating intuitive user interfaces (UI) and enhancing user experiences (UX). Learn design principles, wireframing, prototyping, and usability testing techniques",
    btn: "Get Now ",
  },
  {
    id: "3",
    image: HomeCourse3,
    date: "8 Weeks",
    level: "Intermediate",
    author: "By David Brown",
    title: "Mobile App Development",
    description:
      "Dive into the world of mobile app development. Learn to build native iOS and Android applications using industry-leading frameworks like Swift and Kotlin.",
    btn: "Get Now ",
  },
  {
    id: "4",
    image: HomeCourse4,
    date: "10 Weeks",
    level: "Beginner",
    author: "By Sarah Thompson",
    title: "Graphic Design for Beginners",
    description:
      "Discover the fundamentals of graphic design, including typography, color theory, layout design, and image manipulation techniques. Create visually stunning designs for print and digital media.",
    btn: "Get Now ",
  },
  {
    id: "5",
    image: HomeCourse5,
    date: "10 Weeks",
    level: "Intermediate",
    author: "By Micheal Adams",
    title: "Front-End Web Development",
    description:
      "Become proficient in front-end web development. Learn HTML, CSS, JavaScript, and popular frameworks like Bootstrap and React. Build interactive and responsive websites.",
    btn: "Get Now ",
  },
  {
    id: "6",
    image: HomeCourse6,
    date: "6 Weeks",
    level: "Advance",
    author: "By Jennifer Wilson",
    title: "Advanced JavaScript",
    description:
      "Take your JavaScript skills to the next level. Explore advanced concepts like closures, prototypes, asynchronous programming, and ES6 features. Build complex applications with confidence.",
    btn: "Get Now ",
  },
];

export const testimonialCards = [
  {
    id: "1",
    description:
      "The web design course provided a solid foundation for me. The instructors were knowledgeable and supportive, and the interactive learning environment was engaging. I highly recommend it!",
    image: sarah,
    name: "Sarah L",
    btn: "Read Full Story",
  },
  {
    id: "2",
    description:
      "The UI/UX design course exceeded my expectations. The instructor's expertise and practical assignments helped me improve my design skills. I feel more confident in my career now. Thank you!",
    image: jason,
    name: "Jason M",
    btn: "Read Full Story",
  },
  {
    id: "3",
    description:
      "The mobile app development course was fantastic! The step-by-step tutorials and hands-on projects helped me grasp the concepts easily. I'm now building my own app. Great course!",
    image: emily,
    name: "Emily R",
    btn: "Read Full Story",
  },
  {
    id: "4",
    description:
      "I enrolled in the graphic design course as a beginner, and it was the perfect starting point. The instructor's guidance and feedback improved my design abilities significantly. I'm grateful for this course!",
    image: micheal,
    name: "Micheal K",
    btn: "Read Full Story",
  },
];

export const pricingCards = [
  {
    id: "1",
    title: "Free Plan",
    amount: "$0",
    features: "Available Features",
    textOne: "Unlimited access to all courses",
    textTwo: "Unlimited course materials and resources",
    textThree: "Priority support from instructor",
    textFour: "Course completion certificate",
    textFive: "Ad-free experience",
    textSix: "Access to exclusive Pro Plan community forums",
    textSeven: "Early access to new courses and updates",
  },
  {
    id: "2",
    title: "Pro Plan",
    amount: "$79",
    features: "Available Features",
    textOne: "Unlimited access to all courses",
    textTwo: "Unlimited course materials and resources",
    textThree: "Priority support from instructor",
    textFour: "Course completion certificate",
    textFive: "Ad-free experience",
    textSix: "Access to exclusive Pro Plan community forums",
    textSeven: "Early access to new courses and updates",
  },
  // {
  //   id: "3",
  //   title: "Free Plan",
  //   amount: "$0",
  //   features: "Available Features",
  //   textOne: "Unlimited access to all courses",
  //   textTwo: "Unlimited course materials and resources",
  //   textThree: "Priority support from instructor",
  //   textFour: "Course completion certificate",
  //   textFive: "Ad-free experience",
  //   textSix: "Access to exclusive Pro Plan community forums",
  //   textSeven: "Early access to new courses and updates",
  // },
  // {
  //   id: "4",
  //   title: "Pro Plan",
  //   amount: "$800",
  //   features: "Available Features",
  //   textOne: "Unlimited access to all courses",
  //   textTwo: "Unlimited course materials and resources",
  //   textThree: "Priority support from instructor",
  //   textFour: "Course completion certificate",
  //   textFive: "Ad-free experience",
  //   textSix: "Access to exclusive Pro Plan community forums",
  //   textSeven: "Early access to new courses and updates",
  // },
];

export const coursePages = [
  {
    id: "1",
    img1: webPic1,
    img2: webPic2,
    img3: webPic3,
    date: "4 weeks",
    level: "Beginner",
    author: "By John Smith",
    title: "Web Design Fundamentals",
    description:
      "Learn the fundamentals of web design, including HTML, CSS, and responsive design principles. Develop the skills to create visually appealing and user-friendly websites.",
    btn: "View Course",
    curriculum1: "Introduction to HTML",
    curriculum2: "Styling with CSS",
    curriculum3: "Introduction to Responsive Design",
    curriculum4: "Design Principles for Web",
    curriculum5: "Building a Basic Website",
  },
  {
    id: "2",
    img1: uiPic1,
    img2: uiPic2,
    img3: uiPic3,
    date: "6 weeks",
    level: "Intermediate",
    author: "By Emily Johnson",
    title: "UI/UX Design",
    description:
      "Master the art of creating intuitive user interfaces (UI) and enhancing user experiences (UX). Learn design principles, wireframing, prototyping, and usability testing techniques.",
    btn: "View Course",
    curriculum1: "Introduction to UI/UX Design",
    curriculum2: "User Research and Personas",
    curriculum3: "Wireframing and Prototyping",
    curriculum4: "Visual Design and Branding",
    curriculum5: "Usabilty Testing and Iteration",
  },
  {
    id: "3",
    img1: mobilePic1,
    img2: mobilePic2,
    img3: mobilePic3,
    date: "8 weeks",
    level: "Intermediate",
    author: "By David Brown",
    title: "Mobile App Development",
    description:
      "Dive into the world of mobile app development. Learn to build native iOS and Android applications using industry-leading frameworks like Swift and Kotlin.",
    btn: "View Course",
    curriculum1: "Introduction to Mobile App Development",
    curriculum2: "Fundamentals of Swift Programming (iOS)",
    curriculum3: "Fundamentals of Kotlin Programming (Android)",
    curriculum4: "Building User Interfaces",
    curriculum5: "App Deployment and Testing",
  },
  {
    id: "4",
    img1: graphicPic1,
    img2: graphicPic2,
    img3: graphicPic3,
    date: "10 weeks",
    level: "Beginner",
    author: "By Sarah Thompson",
    title: "Graphic Design for Beginners",
    description:
      "Discover the fundamentals of graphic design, including typography, color theory, layout design, and image manipulation techniques. Create visually stunning designs for print and digital media.",
    btn: "View Course",
    curriculum1: "Introduction to Graphic Design",
    curriculum2: "Topography and Color Theory ",
    curriculum3: "Layout Design and Composition",
    curriculum4: "Image Editing and Manipulation",
    curriculum5: "Design for Print and Digital Media",
  },
  {
    id: "5",
    img1: frontPic1,
    img2: frontPic2,
    img3: frontPic3,
    date: "10 weeks",
    level: "Intermediate",
    author: "By Micheal Adams",
    title: "Front-End Web Development",
    description:
      "Become proficient in front-end web development. Learn HTML, CSS, JavaScript, and popular frameworks like Bootstrap and React. Build interactive and responsive websites.",
    btn: "View Course",
    curriculum1: "HTML Fundamentals",
    curriculum2: "CSS Styling and Layouts",
    curriculum3: "JavaScript Basics",
    curriculum4: "Building Responsive Websites",
    curriculum5: "Introduction to Bootstrap and React",
  },
];

export const AboutCards = [
  {
    id: "1",
    title: "Achievements",
    description:
      "Our commitment to excellence has led us to achieve significant milestones along our journey. Here are some of our notable achievements",
    cardOneT: "Trusted by Thousands",
    cardOnePic: Aone,
    cardOneP:
      "We have successfully served thousands of students, helping them unlock their potential and achieve their career goals.",
    cardTwoT: "Award-Winning Courses",
    cardTwoPic: Atwo,
    cardTwoP:
      "Our courses have received recognition and accolades in the industry for their quality, depth of content, and effective teaching methodologies.",
    cardThreeT: "Positive Student Feedback",
    cardThreePic: Athree,
    cardThreeP:
      "We take pride in the positive feedback we receive from our students, who appreciate the practicality and relevance of our course materials.",
    cardFourT: "Industry Partnerships",
    cardFourPic: Afour,
    cardFourP:
      "We have established strong partnerships with industry leaders, enabling us to provide our students with access to the latest tools and technologies",
  },
  {
    id: "2",
    title: "Our Goals",
    description:
      "At SkillBridge, our goal is to empower individuals from all backgrounds to thrive in the world of design and development. We believe that education should be accessible and transformative, enabling learners to pursue their passions and make a meaningful impact.Through our carefully crafted courses, we aim to",
    cardOneT: "Provide Practical Skills",
    cardOnePic: Bone,
    cardOneP:
      "We focus on delivering practical skills that are relevant to the current industry demands. Our courses are designed to equip learners with the knowledge and tools needed to excel in their chosen field.",
    cardTwoT: "Foster Creative Problem-Solving",
    cardTwoPic: Btwo,
    cardTwoP:
      "We encourage creative thinking and problem-solving abilities, allowing our students to tackle real-world challenges with confidence and innovation.",
    cardThreeT: "Promote Collaboration and Community",
    cardThreePic: Bthree,
    cardThreeP:
      "We believe in the power of collaboration and peer learning. Our platform fosters a supportive and inclusive community where learners can connect, share insights, and grow together.",
    cardFourT: "Stay Ahead of the Curve",
    cardFourPic: Bfour,
    cardFourP:
      "The digital landscape is constantly evolving, and we strive to stay at the forefront of industry trends. We regularly update our course content to ensure our students receive the latest knowledge and skills.",
  },
];

export const singlePages = [
  {
    id: 1,
    title: "Web Design Fundamentals ",
    description:
      "Welcome to our UI/UX Design course! This comprehensive program will equip you with the knowledge and skills to create exceptional user interfaces (UI) and enhance user experiences (UX). Dive into the world of design thinking, wireframing, prototyping, and usability testing. Below is an overview of the curriculum",
    image: CourseDeatails,
    num1: "1",
    OneCardT: "Introduction Wed Design",
    OneCardP1: "Introduction to HTML",
    OneCardP2: "Introduction to HTML5 and syntax",
    OneCardP3: "Introduction to Visual Studio Code",
    lesson1: "Lesson 01",
    lesson2: "Lesson 02",
    lesson3: "Lesson 03",
    time1: "45 minutes",
    time2: "1 Hour",
    time3: "55 minutes",
    num2: "2",
    TwoCardT: "Introduction to CSS",
    TwoCardP1: "Introduction to Font and Styling",
    TwoCardP2: "Introduction to Box Sizing",
    TwoCardP3: "Flex box and Grid positioning",
    lesson1: "Lesson 01",
    lesson2: "Lesson 02",
    lesson3: "Lesson 03",
    time1: "45 minutes",
    time2: "1 Hour 30mins",
    time3: "45 minutes",
    num3: "3",
    ThreeCardT: "Introduction to JavaScript",
    ThreeCardP1: "JavaScript Syntax",
    ThreeCardP2: "Functions in JavaScript",
    ThreeCardP3: "Document Object Model",
    lesson1: "Lesson 01",
    lesson2: "Lesson 02",
    lesson3: "Lesson 03",
    time1: "45 minutes",
    time2: "1 Hour",
    time3: "50 minutes",
    num4: "4",
    FourCardT: "Introduction to Tailwind CSS",
    FourCardP1: "Tailwind Documentation",
    FourCardP2: "Custom Classes in Tailwind",
    FourCardP3: "Tailwind Usage with React",
    lesson1: "Lesson 01",
    lesson2: "Lesson 02",
    lesson3: "Lesson 03",
    time41: "50 minutes",
    time42: "1 Hours 30 Minutes",
    time43: "2 Hours minutes",
    num5: "5",
    FiveCardT: "Introduction to Shadcn and Diasy UI",
    FiveCardP1: "Daisy Ui and Features",
    FiveCardP2: "Shadcn and Features",
    FiveCardP3: "React with Shadcn and Daisy",
    lesson1: "Lesson 01",
    lesson2: "Lesson 02",
    lesson3: "Lesson 03",
    time51: "1 hours",
    time52: "1 Hour 20 Minutes",
    time53: "2 Hours",
  },
  {
    id: 2,
    title: "UI/UX Design Course",
    description:
      "Welcome to our UI/UX Design course! This comprehensive program will equip you with the knowledge and skills to create exceptional user interfaces (UI) and enhance user experiences (UX). Dive into the world of design thinking, wireframing, prototyping, and usability testing. Below is an overview of the curriculum",
    image: CourseDeatails,
    num1: "1",
    OneCardT: "Introduction to UI/UX Design",
    OneCardP1: "Lorem ipsum, dolor sit amet consectetur",
    OneCardP2: "Lorem ipsum, dolor sit amet consectetur",
    OneCardP3: "Lorem ipsum, dolor sit amet consectetur",
    lesson1: "Lesson 01",
    lesson2: "Lesson 02",
    lesson3: "Lesson 03",
    time1: "45 minutes",
    time2: "1 Hour",
    time3: "30 minutes",
    num2: "2",
    TwoCardT: "User Reasearch and Analysis",
    TwoCardP1: "Lorem ipsum, dolor sit amet consectetur ",
    TwoCardP2: "Lorem ipsum, dolor sit amet consectetur ",
    TwoCardP3: "Lorem ipsum, dolor sit amet consectetur ",
    lesson1: "Lesson 01",
    lesson2: "Lesson 02",
    lesson3: "Lesson 03",
    time1: "45 minutes",
    time2: "1 Hour",
    time3: "30 minutes",
    num3: "3",
    ThreeCardT: "Wireframing and Prototyping",
    ThreeCardP1: "Lorem ipsum, dolor sit amet consectetur",
    ThreeCardP2: "Lorem ipsum, dolor sit amet consectetur ",
    ThreeCardP3: "Lorem ipsum, dolor sit amet consectetur ",
    lesson1: "Lesson 01",
    lesson2: "Lesson 02",
    lesson3: "Lesson 03",
    time1: "45 minutes",
    time2: "1 Hour",
    time3: "20 minutes",
    num4: "4",
    FourCardT: "Visual Design and Branding",
    FourCardP1: "Lorem ipsum, dolor sit amet consectetur ",
    FourCardP2: "Lorem ipsum, dolor sit amet consectetur ",
    FourCardP3: "Lorem ipsum, dolor sit amet consectetur ",
    lesson1: "Lesson 01",
    lesson2: "Lesson 02",
    lesson3: "Lesson 03",
    time1: "45 minutes",
    time2: "1 Hour",
    time3: "45 minutes",
    num5: "5",
    FiveCardT: "Usabiliy Testing and Iteration",
    FiveCardP1: "Lorem ipsum, dolor sit amet consectetur ",
    FiveCardP2: "Lorem ipsum, dolor sit amet consectetur ",
    FiveCardP3: "Lorem ipsum, dolor sit amet consectetur ",
    lesson1: "Lesson 01",
    lesson2: "Lesson 02",
    lesson3: "Lesson 03",
    time51: "45 minutes",
    time52: "1 Hour",
    time53: "45 minutes",
  },
  {
    id: 3,
    title: "UI/UX Design Course",
    description:
      "Welcome to our UI/UX Design course! This comprehensive program will equip you with the knowledge and skills to create exceptional user interfaces (UI) and enhance user experiences (UX). Dive into the world of design thinking, wireframing, prototyping, and usability testing. Below is an overview of the curriculum",
    image: CourseDeatails,
    num: "1",
    OneCardT: "Introduction to UI/UX Design",
    OneCardP1: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    OneCardP2: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    OneCardP3: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    lesson1: "Lesson 01",
    lesson2: "Lesson 02",
    lesson3: "Lesson 03",
    time1: "45 minutes",
    time2: "1 Hours",
    time3: "45 minutes",
    num: "2",
    TwoCardT: "User Reasearch and Analysis",
    TwoCardP1: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    TwoCardP2: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    TwoCard3: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    lesson1: "Lesson 01",
    lesson2: "Lesson 02",
    lesson3: "Lesson 03",
    time1: "45 minutes",
    time2: "1 Hours",
    time3: "45 minutes",
    ThreeCardT: "Wireframing and Prototyping",
    ThreeCardP1: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    ThreeCardP2: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    ThreeCard3: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    lesson1: "Lesson 01",
    lesson2: "Lesson 02",
    lesson3: "Lesson 03",
    time1: "45 minutes",
    time2: "1 Hours",
    time3: "45 minutes",
    FourCardT: "Visual Design and Branding",
    FourCardP1: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    FourCardP2: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    FourCardP3: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    lesson1: "Lesson 01",
    lesson2: "Lesson 02",
    lesson3: "Lesson 03",
    time1: "45 minutes",
    time2: "1 Hours",
    time3: "45 minutes",
    FiveCardT: "Usabiliy Testing and Iteration",
    FiveCardP1: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    FiveCardP2: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    FiveCard3: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    lesson1: "Lesson 01",
    lesson2: "Lesson 02",
    lesson3: "Lesson 03",
    time1: "45 minutes",
    time2: "1 Hours",
    time3: "45 minutes",
  },
  {
    id: 4,
    title: "UI/UX Design Course",
    description:
      "Welcome to our UI/UX Design course! This comprehensive program will equip you with the knowledge and skills to create exceptional user interfaces (UI) and enhance user experiences (UX). Dive into the world of design thinking, wireframing, prototyping, and usability testing. Below is an overview of the curriculum",
    image: CourseDeatails,
    num: "1",
    OneCardT: "Introduction to UI/UX Design",
    OneCardP1: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    OneCardP2: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    OneCardP3: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    lesson1: "Lesson 01",
    lesson2: "Lesson 02",
    lesson3: "Lesson 03",
    time1: "45 minutes",
    time2: "1 Hours",
    time3: "45 minutes",
    num: "2",
    TwoCardT: "User Reasearch and Analysis",
    TwoCardP1: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    TwoCardP2: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    TwoCard3: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    lesson1: "Lesson 01",
    lesson2: "Lesson 02",
    lesson3: "Lesson 03",
    time1: "45 minutes",
    time2: "1 Hours",
    time3: "45 minutes",
    ThreeCardT: "Wireframing and Prototyping",
    ThreeCardP1: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    ThreeCardP2: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    ThreeCard3: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    lesson1: "Lesson 01",
    lesson2: "Lesson 02",
    lesson3: "Lesson 03",
    time1: "45 minutes",
    time2: "1 Hours",
    time3: "45 minutes",
    FourCardT: "Visual Design and Branding",
    FourCardP1: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    FourCardP2: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    FourCardP3: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    lesson1: "Lesson 01",
    lesson2: "Lesson 02",
    lesson3: "Lesson 03",
    time1: "45 minutes",
    time2: "1 Hours",
    time3: "45 minutes",
    FiveCardT: "Usabiliy Testing and Iteration",
    FiveCardP1: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    FiveCardP2: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    FiveCard3: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    lesson1: "Lesson 01",
    lesson2: "Lesson 02",
    lesson3: "Lesson 03",
    time1: "45 minutes",
    time2: "1 Hours",
    time3: "45 minutes",
  },
  {
    id: 5,
    title: "UI/UX Design Course",
    description:
      "Welcome to our UI/UX Design course! This comprehensive program will equip you with the knowledge and skills to create exceptional user interfaces (UI) and enhance user experiences (UX). Dive into the world of design thinking, wireframing, prototyping, and usability testing. Below is an overview of the curriculum",
    image: CourseDeatails,
    num: "1",
    OneCardT: "Introduction to UI/UX Design",
    OneCardP1: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    OneCardP2: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    OneCardP3: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    lesson1: "Lesson 01",
    lesson2: "Lesson 02",
    lesson3: "Lesson 03",
    time1: "45 minutes",
    time2: "1 Hours",
    time3: "45 minutes",
    num: "2",
    TwoCardT: "User Reasearch and Analysis",
    TwoCardP1: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    TwoCardP2: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    TwoCard3: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    lesson1: "Lesson 01",
    lesson2: "Lesson 02",
    lesson3: "Lesson 03",
    time1: "45 minutes",
    time2: "1 Hours",
    time3: "45 minutes",
    ThreeCardT: "Wireframing and Prototyping",
    ThreeCardP1: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    ThreeCardP2: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    ThreeCard3: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    lesson1: "Lesson 01",
    lesson2: "Lesson 02",
    lesson3: "Lesson 03",
    time1: "45 minutes",
    time2: "1 Hours",
    time3: "45 minutes",
    FourCardT: "Visual Design and Branding",
    FourCardP1: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    FourCardP2: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    FourCardP3: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    lesson1: "Lesson 01",
    lesson2: "Lesson 02",
    lesson3: "Lesson 03",
    time1: "45 minutes",
    time2: "1 Hours",
    time3: "45 minutes",
    FiveCardT: "Usabiliy Testing and Iteration",
    FiveCardP1: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    FiveCardP2: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    FiveCard3: "Lorem ipsum, dolor sit amet consectetur adipisicing",
    lesson1: "Lesson 01",
    lesson2: "Lesson 02",
    lesson3: "Lesson 03",
    time1: "45 minutes",
    time2: "1 Hours",
    time3: "45 minutes",
  },
];

export const alls = [
  {
    id: "1",
    price: "Fifty quids",
    imgss: sarah,
    block: "bus",
  },
  {
    id: "2",
    price: "Fifty quids",
    imgss: emily,
    block: "com",
  },
  {
    id: "3",
    price: "Fifty quids",
    imgss: jason,
    block: "roobs",
  },
];
